export const FIRSTNAME_ERR = 'Firstname is required'
export const LASTNAME_ERR = 'Lastname is required'
export const EMAIL_EMPTY_ERR = 'Email is required'
export const EMAIL_INVALID_ERR = 'Invalid email format'
export const MOBILE_INVALID_ERR = 'Invalid mobile number'
